/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import Form.QuanlythongtinNV;
import Validication.Check;
import Validication.Icon;
import Validication.getdate;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Insert extends javax.swing.JDialog {

    /**
     * Creates new form Insert
     */
    public Insert(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblCMND.setVisible(false);
        lblDantoc.setVisible(false);
        lblDiachi.setVisible(false);
        lblManv.setVisible(false);
        lblNBD.setVisible(false);
        lblNgaysinh.setVisible(false);
        lblNoiSinh.setVisible(false);
        lblSDT.setVisible(false);
        lblhethanHD.setVisible(false);
        lbltuoi.setVisible(false);
        lblHovaten.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileHinh = new javax.swing.JFileChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        txtHovaten = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgaysinh = new com.toedter.calendar.JDateChooser();
        txtTuoi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboGioitinh = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNoiSinh = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDantoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDienthoai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNgaysinh = new javax.swing.JLabel();
        lblNoiSinh = new javax.swing.JLabel();
        lblCMND = new javax.swing.JLabel();
        lbltuoi = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblDantoc = new javax.swing.JLabel();
        lblDiachi = new javax.swing.JLabel();
        lblhethanHD = new javax.swing.JLabel();
        lblNBD = new javax.swing.JLabel();
        txtngaybatdau = new com.toedter.calendar.JDateChooser();
        txthethanhd = new com.toedter.calendar.JDateChooser();
        btnChon = new javax.swing.JButton();
        lblManv = new javax.swing.JLabel();
        lblHovaten = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã nhân viên");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Họ và tên");

        txtManv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtManv.setCaretColor(new java.awt.Color(255, 255, 255));

        txtHovaten.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtHovaten.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Thông tin chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ngày sinh:");

        txtNgaysinh.setDateFormatString("dd/MM/yyyy");
        txtNgaysinh.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtTuoi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTuoi.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tuổi:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Giới tính:");

        cboGioitinh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cboGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nử", " " }));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nơi Sinh:");

        txtNoiSinh.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNoiSinh.setCaretColor(new java.awt.Color(255, 255, 255));

        txtCMND.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCMND.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CMND:");

        txtDantoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDantoc.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Dân Tộc:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("SĐT:");

        txtDienthoai.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDienthoai.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Địa chỉ:");

        txtDiachi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDiachi.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ngày bắt đầu:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Hết hạn HĐ:");

        lblNgaysinh.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblNoiSinh.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblCMND.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lbltuoi.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblSDT.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblDantoc.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblDiachi.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblhethanHD.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblNBD.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        txtngaybatdau.setDateFormatString("dd/MM/yyyy");
        txtngaybatdau.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txthethanhd.setDateFormatString("dd/MM/yyyy ");
        txthethanhd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnChon.setText("Chọn hình");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel13)))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtngaybatdau, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNBD)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txthethanhd, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtDantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDantoc)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDienthoai))
                    .addComponent(txtNoiSinh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cboGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCMND))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNgaysinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhethanHD)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSDT)
                            .addComponent(lblNoiSinh)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbltuoi, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCMND)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblDiachi)
                        .addGap(30, 30, 30)
                        .addComponent(btnChon)))
                .addGap(73, 73, 73))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(lblNgaysinh)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                            .addComponent(lbltuoi))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(cboGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblCMND))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(txtNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lblNoiSinh, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel11)
                                                    .addComponent(txtDienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(txtDantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lblDantoc)))
                                    .addComponent(lblSDT))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(lblDiachi)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChon)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14))
                    .addComponent(lblhethanHD)
                    .addComponent(lblNBD)
                    .addComponent(txtngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthethanhd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        lblManv.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblHovaten.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        btnthem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblManv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblHovaten)
                .addGap(95, 95, 95))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManv)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHovaten))
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String Hinh;

    public void checkManv(StringBuilder sb) {
        if (Check.checkEmpty(txtManv, sb, "Không để tróng mã nhân viên\n")) {
            if (Check.checkKTDB(txtManv, sb, "Mã nhân viên không được dùng ký tự đặc biệt\n")) {
                lblSDT.setVisible(false);
            } else {
                lblManv.setVisible(true);
            }
        } else {
            lblManv.setVisible(true);
        }

    }

    public void checkHVT(StringBuilder sb) {
        if (Check.checkEmpty(txtHovaten, sb, "Không để tróng Họ và tên\n")) {
            lblHovaten.setVisible(false);
        } else {
            lblHovaten.setVisible(true);
        }

    }

    public void checkNgaySinh(StringBuilder sb) {
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String date = format.format(txtNgaysinh.getDate());
            lblNgaysinh.setVisible(false);
        } catch (Exception e) {
            sb.append("Không để tróng ngày sinh !!!! \n");
            lblNgaysinh.setVisible(true);
        }

    }

    public void checkBatdau(StringBuilder sb) {
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String date = format.format(txtngaybatdau.getDate());
            lblNBD.setVisible(false);

        } catch (Exception e) {
            sb.append("Không để tróng ngày bắt đầu !!!! \n");
            lblNBD.setVisible(true);
        }

    }

    public void checkHethanHD(StringBuilder sb) {
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String date = format.format(txthethanhd.getDate());
            lblhethanHD.setVisible(false);

        } catch (Exception e) {
            sb.append("Không để tróng hết hạn HĐ !!!! \n");
            lblhethanHD.setVisible(true);
        }

    }

    public void checkTuoi(StringBuilder sb) {
        if (Check.checkEmpty(txtTuoi, sb, "Không để tróng tuổi !!!! \n")) {
            try {
                int t = Integer.parseInt(txtTuoi.getText());
                if (t < 18) {
                    sb.append("Tuổi phải lớn hơn 18 \n");
                    lbltuoi.setVisible(true);
                } else {
                    lbltuoi.setVisible(false);
                }
            } catch (Exception e) {
                sb.append("Tuổi không đúng định dạng \n");
                lbltuoi.setVisible(true);
            }
        } else {
            lbltuoi.setVisible(true);
        }

    }

    public void CheckCMND(StringBuilder sb) {
        if (Check.checkEmpty(txtCMND, sb, "Không được để tróng CMND \n")) {
            if (txtCMND.getText().length() != 10) {
                sb.append("CMND không phù hợp \n");
                lblCMND.setVisible(true);
            } else {
                try {
                    long cmnd = Long.parseLong(txtCMND.getText());
                    lblCMND.setVisible(false);
                } catch (Exception e) {
                    sb.append("CMND Không phù hợp \n");
                    lblCMND.setVisible(true);
                }
            }

        } else {
            lblCMND.setVisible(true);
        }
    }

    public void CheckNoiSinh(StringBuilder sb) {
        if (Check.checkEmpty(txtNoiSinh, sb, "Không để tróng nơi sinh")) {
            lblNoiSinh.setVisible(false);
        } else {
            lblNoiSinh.setVisible(true);
        }

    }

    public void CheckDantoc(StringBuilder sb) {
        if (Check.checkEmpty(txtDantoc, sb, "Không để tróng dân tộc")) {
            lblDantoc.setVisible(false);
        } else {
            lblDantoc.setVisible(true);
        }

    }

    public void checkSDT(StringBuilder sb) {
        if (Check.checkEmpty(txtDienthoai, sb, "Không được để tróng SĐT \n")) {
            if (txtDienthoai.getText().length() < 10 || txtDienthoai.getText().length() > 12) {
                sb.append("SĐT không phù hợp \n");
                lblSDT.setVisible(false);
            }
            try {
                long cmnd = Long.parseLong(txtDienthoai.getText());
                lblSDT.setVisible(false);
            } catch (Exception e) {
                sb.append("SĐT Không phù hợp \n");
                lblSDT.setVisible(false);
            }

        } else {
            lblSDT.setVisible(true);
        }
    }

    public void CheckDiachi(StringBuilder sb) {
        if (Check.checkEmpty(txtDiachi, sb, "Không để tróng địa chỉ")) {
            lblDiachi.setVisible(false);
        } else {
            lblDiachi.setVisible(true);
        }

    }

    public boolean checkImage(StringBuilder sb) {

        Icon.SetImage(lblHinh, Hinh, 205, 159, sb);
        if (sb.length() != 0) {
            return false;
        }
        return true;
    }

    public boolean checkImage() {
        StringBuilder sb = new StringBuilder();
        Icon.SetImage(lblHinh, Hinh, 205, 159, sb);
        if (sb.length() != 0) {
            return false;
        }
        return true;
    }

    public boolean check() {
        StringBuilder sb = new StringBuilder();
        checkManv(sb);
        checkHVT(sb);
        checkNgaySinh(sb);
        checkTuoi(sb);
        CheckCMND(sb);
        CheckDiachi(sb);
        CheckDantoc(sb);
        checkSDT(sb);
        CheckNoiSinh(sb);
        checkBatdau(sb);
        checkHethanHD(sb);
        checkImage(sb);
        if (sb.length() != 0) {
            JOptionPane.showMessageDialog(this, sb, "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    String sqlinsert = "insert into QLthongtin values(?,?,?,?,?,?,?,?,?,?,?,?,?)";

    public void insert() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;database=QLNV", "sa", "123");
            PreparedStatement pst = con.prepareStatement(sqlinsert);
            pst.setString(1, txtManv.getText());
            pst.setString(2, txtHovaten.getText());
            pst.setString(3, getdate.Xdate(txtNgaysinh));
            pst.setString((4), txtTuoi.getText());
            pst.setString(5, (String) cboGioitinh.getSelectedItem());
            pst.setString(6, txtCMND.getText());
            pst.setString(7, txtNoiSinh.getText());
            pst.setString(8, txtDantoc.getText());
            pst.setString(9, txtDienthoai.getText());
            pst.setString(10, txtDiachi.getText());
            pst.setString(11, getdate.Xdate(txtngaybatdau));
            pst.setString(12, getdate.Xdate(txthethanhd));
            pst.setString(13, Hinh);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public boolean checkDuplicate() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;database=QLNV", "sa", "123");
            String sql = ("select count(*) from QLthongtin where Manv = ?");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtManv.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getInt(1) == 0) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Trùng mã nhân viên");
                    return false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return false;
    }
    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        if (FileHinh.showOpenDialog(null) == FileHinh.APPROVE_OPTION) {
            Hinh = FileHinh.getSelectedFile().toString();
            if (!checkImage()) {
                JOptionPane.showMessageDialog(this, "Đây không phải là file PNG");
                Hinh = "";
            }
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    
        this.setVisible(false);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (this.check()) {
            if (checkDuplicate()) {
                insert();
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
//                QuanlythongtinNV ql = new QuanlythongtinNV();
//                ql.loadData();
            }
        }
    }//GEN-LAST:event_btnthemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Insert dialog = new Insert(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileHinh;
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnthem;
    private javax.swing.JComboBox<String> cboGioitinh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCMND;
    private javax.swing.JLabel lblDantoc;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHovaten;
    private javax.swing.JLabel lblManv;
    private javax.swing.JLabel lblNBD;
    private javax.swing.JLabel lblNgaysinh;
    private javax.swing.JLabel lblNoiSinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblhethanHD;
    private javax.swing.JLabel lbltuoi;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDantoc;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtDienthoai;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtManv;
    private com.toedter.calendar.JDateChooser txtNgaysinh;
    private javax.swing.JTextField txtNoiSinh;
    private javax.swing.JTextField txtTuoi;
    private com.toedter.calendar.JDateChooser txthethanhd;
    private com.toedter.calendar.JDateChooser txtngaybatdau;
    // End of variables declaration//GEN-END:variables
}
