/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Dialog.InsertLuong;
import Validication.Check;
import Validication.Icon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class QLLuong extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form QLLuong
     */
    public QLLuong() {
        initComponents();
        icon.SetIcon(btnthem, "Icon\\Add1.png", 64);
        icon.SetIcon(btnxoa, "Icon\\delete.png", 64);
        icon.SetIcon(btnLui, "Icon\\previous.png", 64);
        icon.SetIcon(btnTiep, "Icon\\next.png", 64);
        icon.SetIcon(btncapnhat, "Icon\\update.png", 64);
        lblHovaten.setVisible(false);
        lblLuongthang.setVisible(false);
        lblManv.setVisible(false);
        lblnocong.setVisible(false);
        lblthucnhan.setVisible(false);
        lbltiencom.setVisible(false);
        lbltiendth.setVisible(false);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;database=QLNV", "sa", "123");
            pstDelete = con.prepareStatement("delete from QLLuong where manv = ?");
            pstUpdate = con.prepareStatement("Update QLLuong set HVT = ? , LuongThang = ? ,NoCong = ? , TienCom = ? , TienDTh=? where Manv = ?  ");
            pstDetail = con.prepareStatement("Select * ,luongthang-nocong-tiencom-tiendth as 'LuongTN' from QLLuong ", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rts = pstDetail.executeQuery();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        Loaddata();
        Loaddatatop5();
        fill = true;

    }
    Connection con;
    PreparedStatement pstDetail;
    PreparedStatement pstDelete;
    PreparedStatement pstUpdate;
    ResultSet rts;
    Icon icon = new Icon();
    boolean fill = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Vector col5 = new Vector();
    Vector col = new Vector();
    Vector data = new Vector();
    Vector datatop5 = new Vector();
    String sqlfind = "";
    boolean find = false;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnTiep = new javax.swing.JButton();
        btnLui = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTim = new javax.swing.JTextField();
        cboTim = new javax.swing.JComboBox<>();
        btnTim = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        txtHovaten = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtluongthang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnocong = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTiencom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txttiendth = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtthucnhan = new javax.swing.JTextField();
        lblLuongthang = new javax.swing.JLabel();
        lblnocong = new javax.swing.JLabel();
        lbltiendth = new javax.swing.JLabel();
        lbltiencom = new javax.swing.JLabel();
        lblthucnhan = new javax.swing.JLabel();
        lblManv = new javax.swing.JLabel();
        lblHovaten = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltop5 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnThaydoi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(119, 139, 235));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUẢN LÝ LƯƠNG NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(182, 182, 182))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(99, 205, 218));

        btnthem.setContentAreaFilled(false);
        btnthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnthemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnthemMouseExited(evt);
            }
        });
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\Delete.png")); // NOI18N
        btnxoa.setBorderPainted(false);
        btnxoa.setContentAreaFilled(false);
        btnxoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnxoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnxoaMouseExited(evt);
            }
        });
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnTiep.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\next.png")); // NOI18N
        btnTiep.setBorderPainted(false);
        btnTiep.setContentAreaFilled(false);
        btnTiep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTiepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTiepMouseExited(evt);
            }
        });
        btnTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepActionPerformed(evt);
            }
        });

        btnLui.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\previous.png")); // NOI18N
        btnLui.setBorderPainted(false);
        btnLui.setContentAreaFilled(false);
        btnLui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLuiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLuiMouseExited(evt);
            }
        });
        btnLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuiActionPerformed(evt);
            }
        });

        btncapnhat.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\update.png")); // NOI18N
        btncapnhat.setBorderPainted(false);
        btncapnhat.setContentAreaFilled(false);
        btncapnhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncapnhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncapnhatMouseExited(evt);
            }
        });
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLui, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTiep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTiep, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLui, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(61, 193, 211));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_people_100px.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        txtTim.setBackground(new java.awt.Color(204, 204, 204));
        txtTim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        cboTim.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cboTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MaNV", "HVT" }));

        btnTim.setBackground(new java.awt.Color(153, 153, 153));
        btnTim.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_search_36px.png")); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã nhân viên");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Họ và tên");

        txtManv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtManv.setCaretColor(new java.awt.Color(255, 255, 255));
        txtManv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtManvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtManvMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtManvMouseReleased(evt);
            }
        });

        txtHovaten.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtHovaten.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Lương", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        txtluongthang.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtluongthang.setCaretColor(new java.awt.Color(255, 255, 255));
        txtluongthang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtluongthangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtluongthangMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtluongthangMouseReleased(evt);
            }
        });
        txtluongthang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtluongthangActionPerformed(evt);
            }
        });
        txtluongthang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtluongthangKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Lương tháng :");

        txtnocong.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtnocong.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnocong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtnocongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtnocongMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtnocongMouseReleased(evt);
            }
        });
        txtnocong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnocongKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nợ công :");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Tiền cơm :");

        txtTiencom.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTiencom.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTiencom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTiencomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTiencomMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtTiencomMouseReleased(evt);
            }
        });
        txtTiencom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTiencomKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Tiền điện thoại :");

        txttiendth.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txttiendth.setCaretColor(new java.awt.Color(255, 255, 255));
        txttiendth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txttiendthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txttiendthMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txttiendthMouseReleased(evt);
            }
        });
        txttiendth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttiendthKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Thực nhận :");

        txtthucnhan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtthucnhan.setCaretColor(new java.awt.Color(255, 255, 255));
        txtthucnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtthucnhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtthucnhanMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtthucnhanMouseReleased(evt);
            }
        });
        txtthucnhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtthucnhanKeyReleased(evt);
            }
        });

        lblLuongthang.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblnocong.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lbltiendth.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lbltiencom.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblthucnhan.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtthucnhan)
                    .addComponent(txtluongthang, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txtTiencom))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblLuongthang)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnocong, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lbltiencom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttiendth)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnocong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltiendth, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblthucnhan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtluongthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtnocong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLuongthang)
                    .addComponent(lblnocong))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtTiencom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(txttiendth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbltiendth)
                    .addComponent(lbltiencom))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtthucnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblthucnhan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblManv.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        lblHovaten.setIcon(new javax.swing.ImageIcon("F:\\Java\\ProjecAss\\Icon\\icons8_high_priority_30px.png")); // NOI18N

        tbltop5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MãNV", "Họ và tên", "Lương tháng", "Thực nhận"
            }
        ));
        tbltop5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltop5MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbltop5MouseReleased(evt);
            }
        });
        tbltop5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbltop5KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbltop5);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Top 5 nhân viên có lương tháng cao nhất :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblManv)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHovaten))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnTim)))
                .addGap(89, 89, 89))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblManv)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblHovaten))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MãNV", "Họ và tên"
            }
        ));
        tblNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanvienMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblNhanvienMouseReleased(evt);
            }
        });
        tblNhanvien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblNhanvienKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanvien);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("File");

        MnThaydoi.setText("Thay đổi tài khoản");
        MnThaydoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnThaydoiActionPerformed(evt);
            }
        });
        jMenu1.add(MnThaydoi);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Loaddata() {
 
        String sql;
        if (sqlfind.length() != 0) {
            sql = "select Manv,HVT from QLLuong where " + (String) cboTim.getSelectedItem() + " like N'%" + sqlfind + "%'";

        } else {
            sql = "select Manv,HVT from Qlluong ";
        }
        try {
            rts = pstDetail.executeQuery();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            data.clear();
            if (!fill) {
                ResultSetMetaData rsmt = rs.getMetaData();
                col.add(rsmt.getColumnName(1));
                col.add(rsmt.getColumnName(2));

            }
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                data.add(v);
            }

            TableModel tbl = new DefaultTableModel(data, col);
            tblNhanvien.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void Loaddatatop5() {
        
        String sql = "select top 5 manv as N'Mã nhân viên' , hvt as N'Họ và tên' , luongthang as N'Lương tháng', luongthang-nocong-tiencom-tiendth as 'LuongTN' from QLluong order by LuongTN desc ";
        try {
            rts = pstDetail.executeQuery();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            datatop5.clear();
            if (!fill) {
                ResultSetMetaData rsmd = rs.getMetaData();
                col5.add(rsmd.getColumnName(1));
                col5.add(rsmd.getColumnName(2));
                col5.add(rsmd.getColumnName(3));
                col5.add(rsmd.getColumnName(4));
            }
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getLong(3));
                v.add(rs.getLong(4));
                datatop5.add(v);
            }
            TableModel tbl = new DefaultTableModel(datatop5, col5);
            tbltop5.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void delete() {
        try {
            boolean delete = false;
            rts.beforeFirst();
            while (rts.next()) {
                String ma = rts.getString(2);
                if (ma.equalsIgnoreCase(txtManv.getText())) {
                    int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa thông tin lương có mã nhân viên " + ma, "!!!", JOptionPane.YES_NO_OPTION);
                    if (n == JOptionPane.YES_OPTION) {
                        pstDelete.setString(1, ma);
                        pstDelete.executeUpdate();
                        delete = true;
                    } else {
                        delete = true;

                    }
                    break;
                }
            }
            if (delete == false) {
                JOptionPane.showMessageDialog(this, "vui lòng chọn nhân viên muốn xóa");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void update() {
//      set HVT = ? , LuongThang = ? ,NoCong = ? , TienCom = ? , TienDTh=? where Manv = ? 
        try {
            pstUpdate.setString(1, txtHovaten.getText());
            pstUpdate.setLong(2, Long.parseLong(txtluongthang.getText()));
            pstUpdate.setLong(3, Long.parseLong(txtnocong.getText()));
            pstUpdate.setLong(4, Long.parseLong(txtTiencom.getText()));
            pstUpdate.setLong(5, Long.parseLong(txttiendth.getText()));
            pstUpdate.setString(6, txtManv.getText());
            pstUpdate.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void click() {

        try {
            int n = tblNhanvien.getSelectedRow();
            String name = (String) tblNhanvien.getValueAt(n, 0);
            rts.beforeFirst();
            while (rts.next()) {
                if (rts.getString(2).equalsIgnoreCase(name)) {
                    txtManv.setText(rts.getString(2));
                    txtHovaten.setText(rts.getString(3));
                    txtluongthang.setText(String.valueOf(rts.getLong(4)));
                    txtnocong.setText(String.valueOf(rts.getLong(5)));
                    txtTiencom.setText(String.valueOf(rts.getLong(6)));
                    txttiendth.setText(String.valueOf(rts.getLong(7)));
                    txtthucnhan.setText(String.valueOf(rts.getLong(8)));
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void clickTop5() {
        try {
            int n = tbltop5.getSelectedRow();
            String name = (String) tbltop5.getValueAt(n, 0);
            rts.beforeFirst();
            while (rts.next()) {
                if (rts.getString(2).equalsIgnoreCase(name)) {
                    txtManv.setText(rts.getString(2));
                    txtHovaten.setText(rts.getString(3));
                    txtluongthang.setText(String.valueOf(rts.getLong(4)));
                    txtnocong.setText(String.valueOf(rts.getLong(5)));
                    txtTiencom.setText(String.valueOf(rts.getLong(6)));
                    txttiendth.setText(String.valueOf(rts.getLong(7)));
                    txtthucnhan.setText(String.valueOf(rts.getLong(8)));
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void checkManv(StringBuilder sb) {
        Check.checkEmpty(txtManv, sb, "Vui lòng không để tróng mã nhân viên");
    }

    public void checkHVT(StringBuilder sb) {
        Check.checkEmpty(txtHovaten, sb, "Vui lòng không để tróng họ và tên");
    }

    public void checkLuongthang(StringBuilder sb) {
        Check.checkEmpty(txtluongthang, sb, "Vui lòng không để tróng lương tháng");
    }

    public void checkNocong(StringBuilder sb) {
        Check.checkEmpty(txtnocong, sb, "Vui lòng không để tróng nợ công");
    }

    public void checkTiencom(StringBuilder sb) {
        Check.checkEmpty(txtTiencom, sb, "Vui lòng không để tróng tiền cơm");
    }

    public void checkTiendth(StringBuilder sb) {
        Check.checkEmpty(txttiendth, sb, "Vui lòng không để tróng tiền điện thoại");
    }

    public boolean check() {
        StringBuilder sb = new StringBuilder();
        checkManv(sb);
        checkHVT(sb);
        checkLuongthang(sb);
        checkNocong(sb);
        checkTiencom(sb);
        checkTiendth(sb);
        if (sb.length() != 0) {
            JOptionPane.showMessageDialog(this, sb, "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    public void next() {
        try {
            rts.next();
            if (rts.isAfterLast()) {
                rts.beforeFirst();
                rts.next();
                txtManv.setText(rts.getString(2));
                txtHovaten.setText(rts.getString(3));
                txtluongthang.setText(String.valueOf(rts.getLong(4)));
                txtnocong.setText(String.valueOf(rts.getLong(5)));
                txtTiencom.setText(String.valueOf(rts.getLong(6)));
                txttiendth.setText(String.valueOf(rts.getLong(7)));
                txtthucnhan.setText(String.valueOf(rts.getLong(8)));

            } else {
                txtManv.setText(rts.getString(2));
                txtHovaten.setText(rts.getString(3));
                txtluongthang.setText(String.valueOf(rts.getLong(4)));
                txtnocong.setText(String.valueOf(rts.getLong(5)));
                txtTiencom.setText(String.valueOf(rts.getLong(6)));
                txttiendth.setText(String.valueOf(rts.getLong(7)));
                txtthucnhan.setText(String.valueOf(rts.getLong(8)));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void previous() {
        try {
            rts.previous();
            if (rts.isBeforeFirst()) {
                rts.afterLast();
                rts.previous();
                txtManv.setText(rts.getString(2));
                txtHovaten.setText(rts.getString(3));
                txtluongthang.setText(String.valueOf(rts.getLong(4)));
                txtnocong.setText(String.valueOf(rts.getLong(5)));
                txtTiencom.setText(String.valueOf(rts.getLong(6)));
                txttiendth.setText(String.valueOf(rts.getLong(7)));
                txtthucnhan.setText(String.valueOf(rts.getLong(8)));

            } else {
                txtManv.setText(rts.getString(2));
                txtHovaten.setText(rts.getString(3));
                txtluongthang.setText(String.valueOf(rts.getLong(4)));
                txtnocong.setText(String.valueOf(rts.getLong(5)));
                txtTiencom.setText(String.valueOf(rts.getLong(6)));
                txttiendth.setText(String.valueOf(rts.getLong(7)));
                txtthucnhan.setText(String.valueOf(rts.getLong(8)));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    public void find() {
        sqlfind = "";
        sqlfind = txtTim.getText();

    }
    private void btnTiepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiepMouseEntered
        // TODO add your handling code here:
        icon.SetIcon(btnTiep, "Icon\\next1.png", 64);
    }//GEN-LAST:event_btnTiepMouseEntered

    private void btnTiepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiepMouseExited
        // TODO add your handling code here:
        icon.SetIcon(btnTiep, "Icon\\next.png", 64);
    }//GEN-LAST:event_btnTiepMouseExited

    private void btnTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepActionPerformed
        // TODO add your handling code here:

        next();

    }//GEN-LAST:event_btnTiepActionPerformed

    private void btnLuiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuiMouseEntered
        // TODO add your handling code here:
        icon.SetIcon(btnLui, "Icon\\previous1.png", 64);
    }//GEN-LAST:event_btnLuiMouseEntered

    private void btnLuiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuiMouseExited
        // TODO add your handling code here:
        icon.SetIcon(btnLui, "Icon\\previous.png", 64);
    }//GEN-LAST:event_btnLuiMouseExited

    private void btnLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuiActionPerformed
        // TODO add your handling code here:
        previous();

    }//GEN-LAST:event_btnLuiActionPerformed

    private void btncapnhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncapnhatMouseEntered
        // TODO add your handling code here:
        icon.SetIcon(btncapnhat, "Icon\\update1.png", 64);
    }//GEN-LAST:event_btncapnhatMouseEntered

    private void btncapnhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncapnhatMouseExited
        // TODO add your handling code here:
        icon.SetIcon(btncapnhat, "Icon\\update.png", 64);
    }//GEN-LAST:event_btncapnhatMouseExited

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        if (check()) {
            update();
            Loaddata();
            Loaddatatop5();
        }
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        find();
        Loaddata();

    }//GEN-LAST:event_btnTimActionPerformed

    private void txtManvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManvMouseEntered

        txtManv.setEnabled(false);
        
    }//GEN-LAST:event_txtManvMouseEntered

    private void txtManvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManvMouseExited
        // TODO add your handling code here:
        txtManv.setEnabled(true);

    }//GEN-LAST:event_txtManvMouseExited

    private void txtManvMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManvMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManvMouseReleased

    private void tblNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanvienMouseClicked
        // TODO add your handling code here:
        click();

    }//GEN-LAST:event_tblNhanvienMouseClicked

    private void tblNhanvienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanvienMouseReleased
        // TODO add your handling code here:
        if (tblNhanvien.getCellEditor() != null) {
            tblNhanvien.getCellEditor().cancelCellEditing();
        }

    }//GEN-LAST:event_tblNhanvienMouseReleased

    private void txtluongthangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtluongthangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtluongthangMouseEntered

    private void txtluongthangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtluongthangMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtluongthangMouseExited

    private void txtluongthangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtluongthangMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtluongthangMouseReleased

    private void txtnocongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnocongMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnocongMouseEntered

    private void txtnocongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnocongMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnocongMouseExited

    private void txtnocongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnocongMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnocongMouseReleased

    private void txtTiencomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTiencomMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiencomMouseEntered

    private void txtTiencomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTiencomMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiencomMouseExited

    private void txtTiencomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTiencomMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiencomMouseReleased

    private void txttiendthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttiendthMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txttiendthMouseEntered

    private void txttiendthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttiendthMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txttiendthMouseExited

    private void txttiendthMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttiendthMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttiendthMouseReleased

    private void txtthucnhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtthucnhanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthucnhanMouseEntered

    private void txtthucnhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtthucnhanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthucnhanMouseExited

    private void txtthucnhanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtthucnhanMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthucnhanMouseReleased

    private void tbltop5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltop5MouseClicked
        // TODO add your handling code here:
        clickTop5();
    }//GEN-LAST:event_tbltop5MouseClicked

    private void tbltop5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltop5MouseReleased
        // TODO add your handling code here:
        if (tbltop5.getCellEditor() != null) {
            tbltop5.getCellEditor().cancelCellEditing();
        }


    }//GEN-LAST:event_tbltop5MouseReleased

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        delete();
        Loaddata();
        Loaddatatop5();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnxoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoaMouseExited
        // TODO add your handling code here:
        icon.SetIcon(btnxoa, "Icon\\delete.png", 64);
    }//GEN-LAST:event_btnxoaMouseExited

    private void btnxoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoaMouseEntered
        // TODO add your handling code here:
        icon.SetIcon(btnxoa, "Icon\\delete1.png", 64);
    }//GEN-LAST:event_btnxoaMouseEntered

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        InsertLuong luong = new InsertLuong(this, true);
        luong.setVisible(true);
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        if (!luong.isVisible()) {
                            Loaddata();
                            Loaddatatop5();
                            
                            break;
                        }
                        Thread.sleep(2000);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }.start();

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnthemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemMouseExited
        // TODO add your handling code here:
        icon.SetIcon(btnthem, "Icon\\Add1.png", 64);
    }//GEN-LAST:event_btnthemMouseExited

    private void btnthemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemMouseEntered
        // TODO add your handling code here:
        icon.SetIcon(btnthem, "Icon\\Add.png", 64);
    }//GEN-LAST:event_btnthemMouseEntered

    private void txtluongthangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtluongthangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtluongthangActionPerformed

    private void txtluongthangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtluongthangKeyReleased
        // TODO add your handling code here:
        if (!txtluongthang.getText().matches("[0-9]+")) {
            String s = txtluongthang.getText();
            s = s.replaceAll("[^\\d]+", "");
            txtluongthang.setText(s);
        }
    }//GEN-LAST:event_txtluongthangKeyReleased

    private void txtnocongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnocongKeyReleased
        // TODO add your handling code here:
        if (!txtnocong.getText().matches("[0-9]+")) {
            String s = txtnocong.getText();
            s = s.replaceAll("[^\\d]+", "");
            txtnocong.setText(s);
        }
    }//GEN-LAST:event_txtnocongKeyReleased

    private void txtTiencomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiencomKeyReleased
        // TODO add your handling code here:
        if (!txtTiencom.getText().matches("[0-9]+")) {
            String s = txtTiencom.getText();
            s = s.replaceAll("[^\\d]+", "");
            txtTiencom.setText(s);
        }
    }//GEN-LAST:event_txtTiencomKeyReleased

    private void txttiendthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttiendthKeyReleased
        // TODO add your handling code here:
        if (!txttiendth.getText().matches("[0-9]+")) {
            String s = txttiendth.getText();
            s = s.replaceAll("[^\\d]+", "");
            txttiendth.setText(s);
        }
    }//GEN-LAST:event_txttiendthKeyReleased

    private void txtthucnhanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtthucnhanKeyReleased
        // TODO add your handling code here:
        if (!txtthucnhan.getText().matches("[0-9]+")) {
            String s = txtthucnhan.getText();
            s = s.replaceAll("[^\\d]+", "");
            txtthucnhan.setText(s);
        }
    }//GEN-LAST:event_txtthucnhanKeyReleased

    private void tblNhanvienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblNhanvienKeyReleased
        // TODO add your handling code here:
        if (tblNhanvien.getCellEditor() != null) {
            tblNhanvien.getCellEditor().cancelCellEditing();
        }
    }//GEN-LAST:event_tblNhanvienKeyReleased

    private void tbltop5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbltop5KeyReleased
        // TODO add your handling code here:
        if (tblNhanvien.getCellEditor() != null) {
            tblNhanvien.getCellEditor().cancelCellEditing();
        }
    }//GEN-LAST:event_tbltop5KeyReleased

    private void MnThaydoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnThaydoiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
    }//GEN-LAST:event_MnThaydoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnThaydoi;
    private javax.swing.JButton btnLui;
    private javax.swing.JButton btnTiep;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cboTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHovaten;
    private javax.swing.JLabel lblLuongthang;
    private javax.swing.JLabel lblManv;
    private javax.swing.JLabel lblnocong;
    private javax.swing.JLabel lblthucnhan;
    private javax.swing.JLabel lbltiencom;
    private javax.swing.JLabel lbltiendth;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTable tbltop5;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtTiencom;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtluongthang;
    private javax.swing.JTextField txtnocong;
    private javax.swing.JTextField txtthucnhan;
    private javax.swing.JTextField txttiendth;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
